### ISSUE TITLE
DayData endpoints give orders of magnitude too big USD values

### ISSUE THREAD

**Issue by rbval** [Uniswap/uniswap-v3-subgraph#11]
I've been trying out the following subgraphs:
https://thegraph.com/explorer/subgraph/ianlapham/uniswap-v3-subgraph
https://thegraph.com/explorer/subgraph/uniswap/uniswap-v3

The DayData endpoints give many orders of magnitude too big values. An example of too big USD values can be seen with the following query:
```
{
  uniswapDayDatas {
    id
    date
    tvlUSD
    volumeUSD
  }
}
```

Example result:
![image](https://user-images.githubusercontent.com/6399810/118786160-38a8e800-b89a-11eb-8a29-12a873d17343.png)

**Comment by ianlapham** [comment]
Its confusing but the prod version is actually here https://thegraph.com/explorer/subgraph/ianlapham/uniswap-v3-testing

The reason is for testing new changes we need to deploy on new endpoints - but having issues with the graph moving subgraph from testing to this prod endpoint, this is fixed in the current logic on master

**Comment by 7785957** [comment]
fix the rest of the fields as well: liquidity, sqrtPrice
